name: Shutdown

on:
  schedule:
    - cron: '26 8 * * *'

jobs:
  shutdown:
    environment:
      name: 'Production'
    runs-on: ubuntu-latest
    steps:
      - name: Get NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16    # Railway requires NodeJS version 16 or higher
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Redeploy
        # if: github.event.schedule >= '25 8 * * *'
        run: railway up -s ${{secrets.RAILWAY_SERVICE}} --detach
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
      - name: Sleep & wait for Railway to merge the latest 2 running deployments
        run: sleep 2m
        shell: bash
      - name: Shutting down production
        # if: github.event.schedule >= '25 8 * * *'
        run: railway down --yes --json
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
