name: Shutdown

on:
  schedule:
    - cron: '35 19 * * *'

jobs:
  shutdown:
    environment:
      name: 'Production'
    runs-on: ubuntu-latest
    steps:
      - name: Get NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16    # Railway requires NodeJS version 16 or higher
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Shutting down production
        if: github.event.schedule >= '35 19 * * *'
        run: railway down --yes --json
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
